server:
  port: 8089


  tomcat:
    max-http-form-post-size: 20MB
feign:
  client:
    config:
      default:
        loggerLevel: FULL

logging:
  level:
    feign: DEBUG
  config: classpath:conf/logback-local.xml

spring:
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
